### ISSUE TITLE
error during setup docker-compose

### ISSUE THREAD

**Issue by zierbeek** [Atrejoe/Inky-Calendar-Server#106]
hi!
I'm trying to get this one running on my ubuntu vm but I get this issue. Wrong mapping? 

```
2022-11-30 08:03:48.26 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2022-11-30 08:03:48.29 Server      ERROR: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf':  5(Access is denied.)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070005)
```

**Comment by Atrejoe** [comment]
Hi @zierbeek ,

If you are running this on Ubuntu, then the Windows-style file paths will not work.
Is this part of the setup code I provided?

**Comment by zierbeek** [comment]
Yeah unfortunately, when setting up the mysql db.

**Comment by Atrejoe** [comment]
Can you maybe share what you are trying to achieve and how you intend to achieve it?
Just to be sure, MySQL is not being used by InkyCal, it is used Microsoft (MS) SQL server (free, in a docker container). You may be able to change the code base to make it compatible though, if that is something you want.

## If you only want to **run** InkyCal server yourself
it's best to read these instructions: https://github.com/Atrejoe/Inky-Calendar-Server#option-3-with-docker-compose- , basically:
- Create `docker-compose.yml` file with the contents provided
- Create `.env` file with the content provided.

Run `docker-compose up -d` to start the thing.

## If you want to **build-and-run** Inkycal on your own
it's best to use the [docker-compose](https://github.com/Atrejoe/Inky-Calendar-Server/blob/develop/docker-compose.yml) file. It will start two containers:
- plain old MS Sql (_not MySql_) server
- InkyCal server (a .Net Blazor / web api server)

When in doubt, or if you wanty to ask more questiopsn, there is a Discord channel for dicsussions:
https://discord.com/channels/672082714190544899/766426819321790465

ah you already found it :)
