### ISSUE TITLE
Could not open a connection to SQL Server

### ISSUE THREAD

**Issue by whihathac** [Atrejoe/Inky-Calendar-Server#2]
Can we have a version without SQL server? Maybe SQL Lite db or MySql?

**Comment by Atrejoe** [comment]
@whihathac It is possible, but not yet on the roadmap.
The DAL would need some work for this.
Currently the recommended method for running this is using Docker, in which case using SQL server should not be an issue.
If you want to run straight from code, I can imagine you want to use MySQl. Do you have another reason?

**Comment by whihathac** [comment]
Yeah that makes sense. I did end up using the docker version for this. I am wondering how can we export this panel info I've created in one of my local servers and I want to port it out to another local server?

Btw is there a way to disable authentication on local server with a quick flag?

**Comment by Atrejoe** [comment]
Wow, I missed this. I guess these are two feature requests:

- Import / export panel config (#4)
- Auto-authenticate (#5)

Closing this, not creating an issue for MySQL (yet)
